### ISSUE TITLE
How to make it width 100%

### ISSUE THREAD

**Issue by shinokada** [mattjennings/mdsvexamples#10]
I added width 100% but the code and example blocks are about 500px.
How can I make it 100%?

You can see the size difference in the following image.

![image](https://user-images.githubusercontent.com/147320/160113533-73812dc1-5b21-4804-a31e-6920dc1fd57e.png)

**Comment by mattjennings** [comment]
Does this happen with the default Example component? I don't think there's anything that should be enforcing 500px width

**Comment by shinokada** [comment]
It seems that the box width depends what you have.
The following is using the default Example.

![image](https://user-images.githubusercontent.com/147320/160206891-ada27df9-0c2d-4568-9883-36683b3179bb.png)

**Comment by shinokada** [comment]
The solution for me was to add  a div around.

But if I add the div in the Example.svelte, it doesn't work.

<img width="925" alt="image" src="https://user-images.githubusercontent.com/147320/160207339-40827bd2-d639-4e43-b16f-8ae8da66b8b1.png">

![image](https://user-images.githubusercontent.com/147320/160207399-a67fbd6b-f874-4ef6-b30e-eb59395a7988.png)

**Comment by shinokada** [comment]
It seems that I need to import a component in the each svelte example block.
Is there any way that I import once at the top and no need to write it in the svelte example block?

For example:

````
<script>
import {Button} from 'mylib'
</script>

```svelte example
<Button />
```
````

**Comment by mattjennings** [comment]
Not at the moment, it's something I might look into but haven't yet.

Closing this as the topic issue has been solved.
