### ISSUE TITLE
Document relative component imports not supported

### ISSUE THREAD

**Issue by janosh** [mattjennings/mdsvexamples#11]
Very excited about this project! Thanks for putting it together. 👍 

Just tried it out on [`svelte-multiselect`](https://github.com/janosh/svelte-multiselect) and get import errors when using relative imports:

> 10:20:47 AM [vite] Internal server error: Failed to resolve import "../lib/MultiSelect.svelte" from "src/routes/disabled.svx/___mdsvexample___0.svelte". Does the file exist?

Using `import "$lib/MultiSelect.svelte"` as shown in the readme works. I think the requirement to use alias imports should be stated more clearly (or relative imports supported).

**Comment by mattjennings** [comment]
Ah they should be supported, but I think I see why it’s broken. I’ll take a look today.

**Comment by mattjennings** [comment]
should be fixed in 0.0.8!
