### ISSUE TITLE
Example styles do not reload after changes during development

### ISSUE THREAD

**Issue by mattjennings** [mattjennings/mdsvexamples#13]
CSS changes in example style tags do not apply during development until the server is manually restarted. The displayed code updates, but the example doesn't get the new CSS applied.

**Comment by janosh** [comment]
Also encountering this. How difficult of a fix is this?

**Comment by mattjennings** [comment]
From what I remember I had a difficult time tracking this one down, and I didn’t want to spend much more time on it for the inconvenience that it was.

Happy to take a PR on this!

**Comment by mattjennings** [comment]
Fixed in 0.4.1

**Comment by janosh** [comment]
@mattjennings Thanks so much! 🙏 Just tried it out and it's working! That makes things much easier. 🚀
