### ISSUE TITLE
Setting custom Wrapper component through config has no effect

### ISSUE THREAD

**Issue by janosh** [mattjennings/mdsvexamples#19]
[Following the readme](https://github.com/mattjennings/mdsvexamples/tree/196a7d1af68aeab365eb740a92679b486729c489#wrapper), I tried setting a custom component to render examples as follows to no effect.

```js
import adapter from '@sveltejs/adapter-static'
import { mdsvex } from 'mdsvex'
import examples from 'mdsvexamples'
import preprocess from 'svelte-preprocess'

/** @type {import('@sveltejs/kit').Config} */
export default {
  extensions: [`.svelte`, `.svx`, `.md`],

  preprocess: [
    preprocess(),
    mdsvex({
      remarkPlugins: [
        examples,
        { defaults: { Wrapper: `/src/components/Example.svelte` } },
      ],
      extensions: [`.svx`, `.md`],
    }),
  ],

  kit: {
    adapter: adapter(),
  },
}
```

Setting it as code block meta works though:

````md
```svelte example Wrapper="../../components/Example.svelte"
...
```
````

Here's a [StackBlitz repro](https://stackblitz.com/edit/sveltejs-kit-template-default-jalx72?file=src/lib/Example.svelte).

**Comment by mattjennings** [comment]
hey @janosh , thanks for reporting this. I had the wrong syntax in the example for the config 🤦‍♂️ it should be:

```js
remarkPlugins: [
    [examples, { defaults: { Wrapper: `/src/lib/Example.svelte` } }]
]
```

Just needed to add an extra pair of surrounding square brackets. I'll update the README to correct this.

**Comment by mattjennings** [comment]
Actually I do have the correct syntax in the README 😅 so yeah - just make sure you add those extra square brackets.

**Comment by janosh** [comment]
Oops, should have looked at my config more carefully. Sorry for the noise. 🤦 
Also, I should have gotten suspicious that it must be my mistake after looking at your tests and finding them very solid. 👍

**Comment by mattjennings** [comment]
All good!
