### ISSUE TITLE
Update dependency to vite 4.0.0 

### ISSUE THREAD

**Issue by shinokada** [mattjennings/mdsvexamples#20]
When I update vite to 4.0.0, I get an warning:

```
 WARN  Issues with peer dependencies found
.
└─┬ mdsvexamples 0.3.2
  └─┬ unplugin 0.7.2
    └── ✕ unmet peer vite@"^2.3.0 || ^3.0.0-0": found 4.0.0
```

Can you update to vite 4.0.0?

**Comment by mattjennings** [comment]
can you try v0.3.3? https://github.com/mattjennings/mdsvexamples/releases/tag/0.3.3

**Comment by shinokada** [comment]
v0.3.3 has   `"vite": "^3.0.0"`.
As far as I know, It works with vite 4.0.0. 
Are there any concerns that it won't work with vite 4.0.0?

**Comment by mattjennings** [comment]
No. The peer dependency warning came from unplugin, which I updated and doesn’t seem to have vite as a peer dep anymore. 

If you’re not getting the peer dep warning with v0.3.3 then everything is good and I’ll close this issue.

**Comment by shinokada** [comment]
Then can you update package.json?

**Comment by mattjennings** [comment]
It is a devDependency. It is not used when you install it.

Closing this as it is fixed, no peer dependency warning is shown anymore when installing in Vite 4 projects.
