### ISSUE TITLE
Support passing Wrapper as SvelteComponent

### ISSUE THREAD

**Issue by janosh** [mattjennings/mdsvexamples#22]
[Wrapper](https://github.com/mattjennings/mdsvexamples#wrapper) is currently set through an import path to a Svelte component. Would it be possible to allow passing in the component itself?

Reasoning: I'm using a `CodeExample.svelte` component from an NPM package across multiple projects. That component is not in the package's export map, meaning it's accessible as a named export but not a deep import:

```js
import { CodeExample } from "svelte-zoo" // works
import CodeExample from "svelte-zoo/CodeExample.svelte" // doesn't work
```

and so this also doesn't work

```js
Wrapper: `svelte-zoo/CodeExample.svelte`
```

**Comment by mattjennings** [comment]
I think the easiest solution here is to create your own svelte component that just forwards $$props onto CodeExample. 

I’m happy to take a PR that would add support for this use case, in however form.

**Comment by janosh** [comment]
> I think the easiest solution here is to create your own svelte component that just forwards $$props onto CodeExample.

Agreed but it would add boilerplate.

> I’m happy to take a PR that would add support for this use case, in however form.

Good to know! I'll report back if I find time to work on this.

**Comment by mattjennings** [comment]
A bit late, but I've added support for this 0.4.0. See PR #28 or README for notes on how to use.
