### ISSUE TITLE
feat: filename in meta

### ISSUE THREAD

**Issue by jjagielka** [mattjennings/mdsvexamples#23]
Would it be possible to add to `meta` the currently processed file name? I would be able, for example, to add links to GitHub directing straight to the file.

```js
{
  "Wrapper": "/src/routes/utils/ExampleWrapper.svelte",
  "example": true,
  "file": "/src/pages/my_component_doc.md"
}
```

**Comment by mattjennings** [comment]
@jjagielka sorry for the late response on this. I've added this as `filename` and it'll be available in 0.4.0 which I plan to publish today

https://github.com/mattjennings/mdsvexamples/pull/27
