### ISSUE TITLE
Custom Example.svelte needs an extra line at the top

### ISSUE THREAD

**Issue by shinokada** [mattjennings/mdsvexamples#9]
I created `src/lib/Example.svelte` as you suggested in the README.

```
<script>
	// the source of the example is provided as a prop if you want it
	export let src;
</script>

<div
	class="container flex flex-wrap justify-center rounded-xl py-8 mx-auto bg-gradient-to-r bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 p-2 sm:p-6"
>
	<slot name="example" />
</div>

<div class="code">
	<pre class="language-svelte">
		<slot name="code" />
	</pre>
</div>
```

However if I don't add an extra empty line, it messes up the code as you see in the following image.

<img width="697" alt="image" src="https://user-images.githubusercontent.com/147320/160112467-92314887-d16c-4be5-b634-7131ac9284b4.png">

![image](https://user-images.githubusercontent.com/147320/160111749-f7f83dbf-2e8f-4d55-b6bc-38a6b7ab436c.png)

If I add an extra line there is too much space.

<img width="707" alt="image" src="https://user-images.githubusercontent.com/147320/160112405-1ff77509-7cbb-457f-9f96-aa636d65a7da.png">

![image](https://user-images.githubusercontent.com/147320/160112367-9e50469c-06ab-49e7-be18-df611d61ad3a.png)

**Comment by tropicaaal** [comment]
To fix this, ensure that your Example.svelte has no whitespace between your `<pre>` tags and slots

```html
<pre><slot name="code" /></pre>
```

Unsure if this is intentional or not.

**Comment by mattjennings** [comment]
Yeah my bad, the Example in the README mistakenly had whitespace around the pre tag. I've updated it now. Sorry about that!

**Comment by shinokada** [comment]
Thanks. It fixed.
It might be a good idea to mention about it.
